fix(COR-966): external_host field doesn’t work for Helm
Qovery/terraform-provider-qovery pull request #413
Opened 2024-07-17 09:06 UTC by pggb25

2024-07-17 12:33 UTC, ctjhoa requested changes

2024-07-17 12:33 UTC, ctjhoa commented on internal/domain/helm/helm.go
> +	"strings"
```suggestion
	"fmt"
	"strings"
		
	"github.com/AlekSi/pointer"
	"github.com/go-playground/validator/v10"
	"github.com/google/uuid"
	"github.com/pkg/errors"
	"github.com/qovery/qovery-client-go"
```

2024-07-17 12:33 UTC, ctjhoa commented on internal/domain/helm/helm.go
> +	"strings"
Due to linting rule

2024-07-17 12:33 UTC, ctjhoa commented on internal/domain/helm/helm.go
> +		return nil
```suggestion
		return err
```

2024-07-18 18:17 UTC, pggb25 commented on internal/domain/helm/helm.go
> +		return nil
done

2024-07-19 12:43 UTC, mzottola commented on internal/domain/helm/helm.go
> +}
Looks like the this method doesn't return any error. 
The linter will complain iirc @ctjhoa ?

2024-07-19 12:50 UTC, ctjhoa approved these changes

2024-07-19 13:25 UTC, merged